vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|14 Feb 2002 05:50:12 -0000
vti_extenderversion:SR|5.0.2.2623
vti_lineageid:SR|{3A8AB78B-93DD-4E7C-8217-4BF7EE1CD437}
vti_author:SR|WEBSTRIKE\\setcomputing
vti_modifiedby:SR|WEBSTRIKE\\setcomputing
vti_nexttolasttimemodified:TR|14 Feb 2002 05:49:42 -0000
vti_timecreated:TR|13 Feb 2002 23:27:37 -0000
vti_parentlineageid:SR|{CC871F60-40F7-43A3-B9B7-ABFD7268EA74}
vti_cacheddtm:TX|14 Feb 2002 05:50:12 -0000
vti_filesize:IR|12485
vti_backlinkinfo:VX|
