	<%
	HTMLExportStart = "<html><head><title>1 Click DB Export</title></head>"
	HTMLExportEnd = "</body></html>"
	HTMLSearchKeyword = "<span class=""FieldName"">Keyword : </span>"
	HTMLAttribGridEven = "class=""GridEven"""
	HTMLAttribGridOdd = "class=""GridOdd"""
	HTMLAttribBtnMultiDelete = "type=""submit"" class=""submit"" value=""Delete"""
	HTMLAttribBtnMultiSelect = "type=""submit"" class=""submit"" value=""Select"""
	HTMLTextCompare = "=|Exact Match;;Starts With|Starts With;;Contains|Contains;;Like|Like;;In|In;;Is Null|Is Null"
	HTMLGridButtons = "First;;Prev;;paging|smbutton;;Next;;Last;;New;;Search;;DrillDown;;Reset;;Print;;Excel"
	HTMLTrueValue = ""
	HTMLFalseValue = ""
	HTMLAttribFindBtn = "type=""submit"" value=""search"" class=""submit"""
	HTMLAttribCancelBtn = "type=""submit"" value=""Cancel"" class=""Submit"""
	HTMLSearchBetween = "BETWEEN"
	HTMLSearchBetweenAnd = "AND"
	HTMLAttribGrid = ""
	HTMLSearchAll = "Match&nbsp;All "
	HTMLSearchAny = "Match&nbsp;Any "
	HTMLSearchAnd = " AND "
	HTMLSearchOr = " OR "
	HTMLMemoContinues = " <span class=""Notice"">Continues...</span>"

	HTMLBinaryValue = "<span class=""Information"">Binary&nbsp;Data</span>"
	HTMLNullValue = "&nbsp;"
	HTMLEditLink = "Edit"
	HTMLDetailLink = "Detail"
	HTMLSearchReSet = "Reset"
	HTMLDeleteLink = ""
	HTMLEditLink = "Edit"
	HTMLAscText = "low To high"
	HTMLDescText = "high To low"
	HTMLSortASCLink = "<small>A-Z"
	HTMLSortDESCLink = "<small>Z-A</small>"
	HTMLFilterLink = "<small>fltr</small>"

%>
