<?php require_once('../Connections/saquabb.php'); ?>
<?php
mysql_select_db($database_saquabb, $saquabb);
$query_coment = "SELECT * FROM comentarios WHERE aprovado = 'y' ORDER BY id DESC";
$coment = mysql_query($query_coment, $saquabb) or die(mysql_error());
$row_coment = mysql_fetch_assoc($coment);
$totalRows_coment = mysql_num_rows($coment);
?>   
<html>
<head>
<link rel="stylesheet" type="text/css" >
<!--Code generated by Cool Web Scrollbars from Harmony Hollow Software-->
<!--http://www.harmonyhollow.net-->
<STYLE type="text/css">
<!--
BODY {
	scrollbar-face-color:#ffffff;
	scrollbar-highlight-color:#ffffff;
	scrollbar-3dlight-color:#ffffff;
	scrollbar-darkshadow-color:#ffffff;
	scrollbar-shadow-color:#ffffff;
	scrollbar-arrow-color:#999999;
	scrollbar-track-color:#ffffff;
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
	background-color: #FFFFFF;
}
.style1 {
	font-size: 10px;
	font-family: Verdana, Arial, Helvetica, sans-serif;
	color: #003366;
}
body,td,th {
	color: #000000;
}
a:hover {
	color: #000000;
	text-decoration: underline;
}
h1 {
	color: #000000;
}
a:link {
	color: #000000;
	text-decoration: underline;
}
a:visited {
	color: #000000;
	text-decoration: underline;
}
a:active {
	color: #000000;
	text-decoration: underline;
}
.fonte {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 10px;
	font-style: normal;
	font-weight: bolder;
	color: #000000;
}
.dados {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 10px;
	font-weight: lighter;
	color: #333333;
}
.linha {
	border-top-width: 1px;
	border-right-width: 1px;
	border-bottom-width: 1px;
	border-left-width: 1px;
	border-top-style: none;
	border-right-style: none;
	border-bottom-style: solid;
	border-left-style: none;
	border-top-color: #000000;
	border-right-color: #000000;
	border-bottom-color: #000000;
	border-left-color: #000000;
}
.nome {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 11px;
	font-weight: bolder;
	color: #669933;
}
-->
</STYLE>
<!--End Cool Web Scrollbars code-->
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head>
<body>
<body>
<table width="275" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="275" align="center" valign="top"><?php do { ?>
        <table width="275" border="0" cellpadding="0" cellspacing="4" class="linha">
          <tr>
            <td width="267" align="left"><span class="fonte">Nome:</span> <span class="nome"><?php echo $row_coment['nome']; ?></span></td>
          </tr>
          <tr>
            <td align="left"><span class="fonte">E-mail: </span><span class="dados"><?php echo $row_coment['mail']; ?></span></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="fonte">Cidade: <span class="dados"><?php echo $row_coment['cidade']; ?></span></td>
          </tr>
          <tr>
            <td align="left" valign="top"><span class="fonte">Coment&aacute;rio:</span><span class="dados"> <?php echo $row_coment['comentario']; ?></span><br />
            <br /></td>
          </tr>
        </table>
        <?php } while ($row_coment = mysql_fetch_assoc($coment)); ?></td>
  </tr>
</table>
</body>
</html>
<?php
mysql_free_result($coment);
?>
