<?php require_once('../Connections/saquabb.php'); ?>
<?php
// Load the tNG classes
require_once('../includes/tng/tNG.inc.php');

$maxRows_fotos = 2;
$pageNum_fotos = 0;
if (isset($_GET['pageNum_fotos'])) {
  $pageNum_fotos = $_GET['pageNum_fotos'];
}
$startRow_fotos = $pageNum_fotos * $maxRows_fotos;

mysql_select_db($database_saquabb, $saquabb);
$query_fotos = "SELECT * FROM fotos ORDER BY id_foto DESC";
$query_limit_fotos = sprintf("%s LIMIT %d, %d", $query_fotos, $startRow_fotos, $maxRows_fotos);
$fotos = mysql_query($query_limit_fotos, $saquabb) or die(mysql_error());
$row_fotos = mysql_fetch_assoc($fotos);

if (isset($_GET['totalRows_fotos'])) {
  $totalRows_fotos = $_GET['totalRows_fotos'];
} else {
  $all_fotos = mysql_query($query_fotos);
  $totalRows_fotos = mysql_num_rows($all_fotos);
}
$totalPages_fotos = ceil($totalRows_fotos/$maxRows_fotos)-1;
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head profile="http://gmpg.org/xfn/11"><title>Galeria de fotos at bravus.net</title>




	
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="content-language" content="pt-br">
	<meta name="generator" content="WordPress 2.0.4">
	<meta name="template" content="K2 Beta Two r167">
 	<meta name="description" content="Resenhas, entretenimento e opniões">
    <meta name="keywords" content="Cinema, Filmes, Publicidade, Propaganda, Fotografia">
    <meta name="robots" content="index,follow">
    <meta name="author" content="Office Bravus">
	<link rel="stylesheet" type="text/css" media="screen" href="Galeria%20de%20fotos%20at%20bravus.net_arquivos/style.css">
	<link rel="shortcut icon" href="http://www.officebravus.com/galeria-de-fotos/favicon.ico">

	
	<link rel="alternate" type="application/rss+xml" title="RSS 2.0" href="http://www.officebravus.com/feed/">
	<link rel="alternate" type="text/xml" title="RSS .92" href="http://www.officebravus.com/feed/rss/">
	<link rel="alternate" type="application/atom+xml" title="Atom 0.3" href="http://www.officebravus.com/feed/atom/">

	<link rel="pingback" href="http://www.officebravus.com/xmlrpc.php">
	
	



	<link rel="archives" title="Novembro 2006" href="http://www.officebravus.com/2006/11/">
	<link rel="archives" title="Outubro 2006" href="http://www.officebravus.com/2006/10/">
	<link rel="archives" title="Setembro 2006" href="http://www.officebravus.com/2006/09/">
	<link rel="archives" title="Agosto 2006" href="http://www.officebravus.com/2006/08/">

	<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://www.officebravus.com/xmlrpc.php?rsd">
<script type="text/javascript">
/* Start Of Javascript Generated By WP-EMail 2.07 */
/* <![CDATA[ */
	function email_popup(email_url) {
		window.open(email_url, "_blank", "width=500,height=500,toolbar=0,menubar=0,location=0,resizable=0,scrollbars=1,status=0");
	}
/* ]]> */
/* End Of Javascript Generated By WP-EMail 2.07 */
</script>
<script type="text/javascript">
/* Start Of Javascript Generated By WP-PostRatings 1.04 */
/* <![CDATA[ */
	if(site_url != 'http://www.officebravus.com' || ajax_url != '/index.php') {
		var site_url = 'http://www.officebravus.com';
		var ajax_url = '/index.php';
	}
	var ratings_image = 'stars';
	var ratings_max = '5';
	var ratings_mouseover_image = new Image();
	ratings_mouseover_image.src = site_url + '/wp-content/plugins/postratings/images/' + ratings_image + '/rating_over.gif';
/* ]]> */
/* End Of Javascript Generated By WP-PostRatings 1.04 */
</script>
<script src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/tw-sack.js" type="text/javascript"></script>
<script src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/postratings-js.js" type="text/javascript"></script>
<link rel="stylesheet" href="Galeria%20de%20fotos%20at%20bravus.net_arquivos/postratings-css.css" type="text/css" media="screen">
<style type="text/css" media="screen">

/* Begin Contact Form ][ CSS */
.contactform {
	position: static;
	overflow: hidden;
}

.contactleft {
	width: 25%;
	text-align: right;
	clear: both;
	float: left;
	display: inline;
	padding: 4px;
	margin: 5px 0;
    font-weight: bold;
}

.contactright {
	width: 70%;
	text-align: left;
	float: right;
	display: inline;
	padding: 4px;
	margin: 5px 0;
}

.contacterror {
	border: 2px solid #ff0000;
}
/* End Contact Form ][ CSS */

	</style>


	
<link rel="stylesheet" href="Galeria%20de%20fotos%20at%20bravus.net_arquivos/lightbox.css" type="text/css" media="screen"></head><body class="">

<!-- GOOGLE ANALYTICS -->
<script src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-785130-1";
urchinTracker();
</script>
<!-- FIM DO GOOGLE ANALYTICS -->

<!-- INICIO EFEITOS NA VISUALIZA��O DAS FOTOS -->
<script type="text/javascript" src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/prototype.js"></script>
<script type="text/javascript" src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/scriptaculous.js"></script><script type="text/javascript" src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/effects.js"></script>
<script type="text/javascript" src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/lightbox.js"></script>

<!-- FIM EFEITOS NA VISUALIZA��O DAS FOTOS -->

<div id="top_layout"></div>
<div id="page">

	<div align="center">
    <div id="header">
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" id="header" align="middle" height="200" width="658">
      <param name="allowScriptAccess" value="sameDomain">
      <param name="movie" value="http://www.officebravus.com/wp-content/themes/black-minimalism-10/images/header.swf">
      <param name="quality" value="high">
      <param name="bgcolor" value="#ffffff">
      <param name="wmode" value="transparent">
      <embed src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/header.swf" quality="high" bgcolor="#ffffff" wmode="transparent" allowscriptaccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" align="middle" height="200" width="658">
      
    </object>
		<ul class="menu">
			<li class="page_item"><a href="http://www.officebravus.com/">Blog</a></li>
			<li class="page_item"><a href="http://www.officebravus.com/portifolio/" title="Portifólio">Portifólio</a></li>
<li class="page_item current_page_item"><a href="http://www.officebravus.com/galeria-de-fotos/" title="Galeria de fotos">Galeria de fotos</a></li>
<li class="page_item"><a href="http://www.officebravus.com/curriculos/" title="Quem Somos">Quem Somos</a></li>
<li class="page_item"><a href="http://www.officebravus.com/assine/" title="Assine">Assine</a></li>
<li class="page_item"><a href="http://www.officebravus.com/contato/" title="Contato">Contato</a></li>

<!-- RETIRADO O ITEM PARA O LINK DE ADMIN DO MENU -->
<!--			 -->
		</ul>
	
	</div></div>

		<hr>

<div class="content">
	
	<div class="primary">

    
		<div class="item">

			<div class="pagetitle">
				<h2 id="post-17"><a href="http://www.officebravus.com/galeria-de-fotos/" rel="bookmark" title="Permanent Link to &quot;Galeria de fotos&quot;">Galeria de fotos</a></h2>
		  </div>
		
			<div class="itemtext">
				<div align="center"><img src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/pic_galeria.jpg" height="74" width="658"></div>
<table align="center" border="0" cellpadding="0" cellspacing="0" width="591">
<tbody>
<tr>
<td width="148">&nbsp;</td>
<td width="148">
  <?php do { ?>
    <div align="center"><a rel="lightbox[galeria]" href="<?php echo tNG_showDynamicImage("../", "../uploads/fotos/", "{fotos.arquivo}");?>"><img src="<?php echo tNG_showDynamicThumbnail("../", "../uploads/fotos/", "{fotos.arquivo}", 140, 100, false); ?>" border="0"></a></div>
    <?php } while ($row_fotos = mysql_fetch_assoc($fotos)); ?></td>
<td width="148"><a rel="lightbox[galeria]" href="<?php echo tNG_showDynamicImage("../", "../uploads/fotos/", "{fotos.arquivo}");?>"></a>
  <div align="center"><a rel="lightbox[galeria]" href="<?php echo tNG_showDynamicImage("../", "../uploads/fotos/", "{fotos.arquivo}");?>"><img src="<?php echo tNG_showDynamicThumbnail("../", "../uploads/fotos/", "{fotos.arquivo}", 140, 100, false); ?>" border="0" /></a></div></td>
<td width="147">
<div align="center"><a rel="lightbox[galeria]" href="http://officebravus.com/images/52.jpg"><img src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/tumb_52.jpg" border="0" height="113" width="148"></a></div></td>
</tr>
</tbody></table>
	
		  </div>

		</div>

				
	</div>

	<div id="sidebar">
<a href="http://www.officebravus.com/curriculos/rodrigo/"><img src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/rodrigo.jpg" class="fellas" border="0"></a><a href="http://www.officebravus.com/curriculos/marquinhos/"><img src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/marquinhos.jpg" class="fellas" border="0"></a><a href="http://www.officebravus.com/curriculos/denis/"><img src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/denis.jpg" class="fellas" border="0"></a>
<br><br><br><br>
<a href="http://www.tarjapreta.org/" target="_blank"><img src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/bt_tarja.gif" alt="Tarja Preta"></a>
<a href="http://omedi.blogspot.com/" title="O maior espetáculo da internet" target="_blank"><img src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/Banner_OMEdI_01.gif" alt="Omedi" title="O maior espetáculo da internet"></a>
<a href="http://www.jacarebanguela.com.br/" target="_blank"><img src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/jb6xj.png" alt="Jacaré Banguela"></a>
<a href="http://noelnetblog.blogspot.com/" target="_blank"><img src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/gifnoelnovo7ty.gif" alt="Blog do Noel"></a>
<a href="http://www.sedentario.org/blog/" rel="friend" target="_blank"><img src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/botaosh8bf1bo.gif" alt="Sedentário e Hiperativo"></a>
</div>

</div>
	
<br class="clear">

</div> <!-- Close Page -->

<div align="center"><div id="footer">
	<!-- 21 queries. 0.538 seconds. -->



</div></div>

<div style="display: none;" id="overlay"></div><div style="display: none;" id="lightbox"><div id="outerImageContainer"><div id="imageContainer"><img id="lightboxImage"><div id="hoverNav"><a href="#" id="prevLink"></a><a href="#" id="nextLink"></a></div><div id="loading"><a href="#" id="loadingLink"></a></div></div></div><div class="clearfix" id="imageDataContainer"><div id="imageData"><div id="imageDetails"><span id="caption"></span><span id="numberDisplay"></span></div><div id="bottomNav"><a href="#" id="bottomNavClose"><img src="Galeria%20de%20fotos%20at%20bravus.net_arquivos/closelabel.gif"></a></div></div></div></div></body></html>
<?php
mysql_free_result($fotos);
?>