<!-- #include file="connectionstring.asp" -->
              
<html>
<head>
<link rel="stylesheet" type="text/css" >
<!--Code generated by Cool Web Scrollbars from Harmony Hollow Software-->
<!--http://www.harmonyhollow.net-->
<STYLE type="text/css">
<!--
BODY {
	scrollbar-face-color:#ffffff;
	scrollbar-highlight-color:#ffffff;
	scrollbar-3dlight-color:#ffffff;
	scrollbar-darkshadow-color:#ffffff;
	scrollbar-shadow-color:#ffffff;
	scrollbar-arrow-color:#ff3399;
	scrollbar-track-color:#ffffff;
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
	background-color: #FFFFFF;
}
.style1 {
	font-size: 10px;
	font-family: Verdana, Arial, Helvetica, sans-serif;
	color: #FF3399;
}
body,td,th {
	color: #000000;
}
a:hover {
	color: #000000;
	text-decoration: underline;
}
h1 {
	color: #000000;
}
a:link {
	color: #000000;
	text-decoration: underline;
}
a:visited {
	color: #000000;
	text-decoration: underline;
}
a:active {
	color: #000000;
	text-decoration: underline;
}
-->
</STYLE>
<!--End Cool Web Scrollbars code-->
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head>
<body>
<span class="style1">
<%
dim sql
dim CS
dim RS
dim x

' objects
Set CS = Server.CreateObject("ADODB.Connection")
Set RS = Server.CreateObject("ADODB.Recordset")

' connection string (info in connectionstring.asp)
CS.ConnectionString = dbasepath
CS.Provider = provider
CS.Open

sql = "SELECT TOP 50 * FROM shoutbox ORDER BY postID DESC"

Set RS = CS.Execute(sql)

Response.Write "<p align=left>"

while RS.EOF = false
 
	Response.Write "<strong>" & RS("name") &  "</strong>" 
	Response.Write "<br><hr size=1 noshade color=#ffffff>"
	Response.Write "<strong><em>Mensagem:</em></strong>"
    Response.Write "<br>"
	Response.Write "" & RS("post") & ""
	Response.Write "<br>"
	Response.Write "<br>"	
	Response.Write "<em>" & RS("pdate") & "</em>"
	Response.Write "<br><hr size=2 noshade color=#ff3399>"
	
	RS.MoveNext
	
wend
 
Response.Write "</p>"
%>
</span>
</body>
</html>
