<%@ Language=VBScript %>


              
<%
' ban ip addresses
' if Request.ServerVariables("REMOTE_ADDR") = "127.0.0.1" then
' response.redirect("banned.asp")
' end if
%>

<HTML>
<HEAD>
<!--Code generated by Cool Web Scrollbars from Harmony Hollow Software-->
<!--http://www.harmonyhollow.net-->
<STYLE type="text/css">
<!--
BODY {
scrollbar-face-color:#FFFFFF;
scrollbar-highlight-color:#FFFFFF;
scrollbar-3dlight-color:#FFFFFF;
scrollbar-darkshadow-color:#FFFFFF;
scrollbar-shadow-color:#FFFFFF;
scrollbar-arrow-color:#808080;
scrollbar-track-color:#FFFFFF;
}
-->
</STYLE>
<!--End Cool Web Scrollbars code-->

<title>View shouts</title>
<link rel="stylesheet" type="text/css" href="styles/sb.css">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><style type="text/css">
<!--
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
	background-color: #000000;
}
.style3 {color: #FFFFFF}
body,td,th {
	color: #FFFFFF;
}
-->
</style>
</HEAD>
<BODY scroll="no">
<iframe src="sframe.asp" width="169" height="422" frameborder="no"><br>
Seu Browser n&atilde;o suporta Frames </iframe>
<p align="right">&nbsp;</p>

</BODY>
</HTML>
