<?php require_once('Connections/xpress.php'); ?>
<?php
// Load the tNG classes
require_once('includes/tng/tNG.inc.php');

$colname_equipe = "-1";
if (isset($_GET['id'])) {
  $colname_equipe = (get_magic_quotes_gpc()) ? $_GET['id'] : addslashes($_GET['id']);
}
mysql_select_db($database_xpress, $xpress);
$query_equipe = sprintf("SELECT * FROM equipe WHERE id = %s ORDER BY id DESC", $colname_equipe);
$equipe = mysql_query($query_equipe, $xpress) or die(mysql_error());
$row_equipe = mysql_fetch_assoc($equipe);
$totalRows_equipe = mysql_num_rows($equipe);
?>
<html>
<head>
<link rel="stylesheet" type="text/css" href="styles/sb.css">
<script language="JavaScript" src="banco_de_dados/java.js"></script>
<!--Code generated by Cool Web Scrollbars from Harmony Hollow Software-->
<!--http://www.harmonyhollow.net-->
<STYLE type="text/css">
<!--
BODY {
	scrollbar-face-color:#ffffff;
	scrollbar-highlight-color:#ffffff;
	scrollbar-3dlight-color:#ffffff;
	scrollbar-darkshadow-color:#ffffff;
	scrollbar-shadow-color:#ffffff;
	scrollbar-arrow-color:#003366;
	scrollbar-track-color:#ffffff;
	background-color:#FFFFFF;
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
}
body,td,th {
	color: #000000;
	font-family: Verdana, Arial, Helvetica, sans-serif;
}
a:hover {
	color: #CC0000;
	text-decoration: none;
}
h1 {
	color: #ffffff;
}
a:link {
	color: #000000;
	text-decoration: none;
}
a:visited {
	color: #000000;
	text-decoration: none;
}
a:active {
	color: #000000;
	text-decoration: none;
}
.borda {border: 1px solid #000000;}
.style19 {color: #000000}
.style6 {color: #FFFFFF}
.style29 {color: #000000; font-weight: bold; }
a {
	font-size: 10px;
}
.borda_topo {
	border-top-style: solid;
	border-right-style: none;
	border-bottom-style: none;
	border-left-style: none;
	border-top-color: #000000;
	border-right-color: #000000;
	border-bottom-color: #000000;
	border-left-color: #000000;
	border-top-width: 1px;
	border-right-width: 1px;
	border-bottom-width: 1px;
	border-left-width: 1px;
}
.brdnoticia {border: 1px solid #000000;}
.style11 {font-size: 10px}
.style12 {	font-size: 14px;
	color: #000000;
}
.style2 {font-family: Verdana, Arial, Helvetica, sans-serif}
.style36 {font-size: 12px}
.style37 {font-size: 18px}
.style38 {font-size: 10px; font-family: Verdana, Arial, Helvetica, sans-serif; }
-->
</STYLE>
<!--End Cool Web Scrollbars code-->
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head>
<body>
<div align="center">
  <table width="500" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
      <th scope="col"><table width="500" border="0" align="center" cellpadding="0" cellspacing="0">
        
        <tr>
          <th width="428" scope="col"><table width="488" border="0" cellpadding="0" cellspacing="4">
              <tr>
                <td align="center" valign="top"><span class="style37"><?php echo $row_equipe['nome']; ?></span></td>
                <td width="164" rowspan="2" align="left" valign="top"><table width="44" border="1" cellpadding="0" cellspacing="2" bordercolor="#000000" bgcolor="#FFFFFF">
                  <tr>
                    <td width="36"><img src="<?php echo tNG_showDynamicThumbnail("", "uploads/fotos/", "{equipe.foto}", 200, 0, true); ?>" /></td>
                  </tr>
                </table></td>
              </tr>
              <tr>
                <td width="318" align="left" valign="top" class="style38"><?php echo $row_equipe['descricao']; ?></td>
                </tr>
              <tr>
                <td colspan="2">&nbsp;</td>
              </tr>
          </table></th>
        </tr>
      </table></th>
    </tr>
  </table>
</div>
</body>
</html>
<?php
mysql_free_result($equipe);
?>
<%
RsVer_atleta.Close()
Set RsVer_atleta = Nothing
%>
<%
Fotos.Close()
Set Fotos = Nothing
%>
